import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
  project7Laptop,
  project7Mobile,
  project8Laptop,
  project8Mobile,
  project9Laptop,
  project9Mobile,
  project10Laptop,
  project10Mobile,
  project11Laptop,
  project11Mobile,
  project12Laptop,
  project12Mobile,
} from "./projectImages";

export const projectData = [
  {
    id: 7,
    image: project7Laptop,
    transitionImage: project7Mobile,
    title: "Class Closet",
    codeLink: "",
    liveLink: "https://classyclosets.com/",
  },
  {
    id: 8,
    image: project8Laptop,
    transitionImage: project8Mobile,
    title: "BCT",
    codeLink: "",
    liveLink: "https://www.bcthk.com/zh",
  },
  {
    id: 9,
    image: project9Laptop,
    transitionImage: project9Mobile,
    title: "True CBD Cannabis",
    codeLink: "",
    liveLink: "https://matruecannabis.com/en/",
  },
  {
    id: 11,
    image: project11Laptop,
    transitionImage: project11Mobile,
    title: "Hayu",
    codeLink: "",
    liveLink: "https://get.hayu.com/welcome?geo=HK",
  },
  {
    id: 12,
    image: project12Laptop,
    transitionImage: project12Mobile,
    title: "Hello Fresh",
    codeLink: "",
    liveLink: "https://www.hellofresh.com/",
  },
  {
    id: 1,
    image: project1Laptop,
    transitionImage: project1Mobile,
    title: "A meditation app",
    codeLink: "https://github.com/pabaross/meditation-app",
    liveLink: "https://umatter.netlify.app/",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "Restaurant Website",
    codeLink: "https://github.com/pabaross/lediable-restaurant",
    liveLink: "https://lediable.netlify.app/",
  },
  {
    id: 3,
    image: project3Laptop,
    transitionImage: project3Mobile,
    title: "Interior Design Company",
    codeLink: "https://github.com/pabaross/elegancev1",
    liveLink: "https://eleganceee.netlify.app/",
  },
  {
    id: 4,
    image: project4Laptop,
    transitionImage: project4Mobile,
    title: "IT Company",
    codeLink: "https://github.com/pabaross/coderig-landing-page",
    liveLink: "https://codeegrid.netlify.app/",
  },
  {
    id: 5,
    image: project5Laptop,
    transitionImage: project5Mobile,
    title: "Gym Fitness Website",
    codeLink: "https://github.com/pabaross/intrepide",
    liveLink: "https://intrepide.netlify.app/",
  },
  {
    id: 6,
    image: project6Laptop,
    transitionImage: project6Mobile,
    title: "Space Tourism",
    codeLink: "https://github.com/pabaross/space-tourism",
    liveLink: "https://spacetourism-monciego.netlify.app/",
  },
  {
    id: 10,
    image: project10Laptop,
    transitionImage: project10Mobile,
    title: "Wedding",
    codeLink: "",
    liveLink: "https://www.anniversaire.co.jp/",
  },
];
